-- AlterTable
ALTER TABLE `voting_events` ADD COLUMN `randomizeOptionOrder` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `audit_logs` MODIFY COLUMN `action` ENUM('EVENT_CREATED', 'EVENT_UPDATED', 'EVENT_PUBLISHED', 'EVENT_UNPUBLISHED', 'EVENT_OPENED', 'EVENT_CLOSED', 'EVENT_ARCHIVED', 'EVENT_DUPLICATED', 'OPTION_CREATED', 'OPTION_UPDATED', 'OPTION_DEACTIVATED', 'OPTION_DELETED', 'OPTIONS_REORDERED', 'VOTE_SUBMITTED', 'VOTE_DUPLICATE_BLOCKED', 'VOTE_SESSION_LIMIT_BLOCKED', 'VOTE_REJECTED', 'VOTE_FLAGGED_SUSPICIOUS', 'VOTE_INVALIDATED', 'VOTE_RESTORED', 'VOTE_VOIDED_FOR_REVOTE', 'VOTER_SESSION_CREATED', 'VOTER_IDENTITY_CLAIMED', 'VOTER_BLOCKED', 'VOTER_UNBLOCKED', 'VOTER_SESSION_BLOCKED', 'RATE_LIMIT_TRIGGERED', 'SUSPICIOUS_ACTIVITY_DETECTED', 'CAPTCHA_FAILED', 'ADMIN_LOGIN_SUCCEEDED', 'ADMIN_LOGIN_FAILED', 'ADMIN_LOGGED_OUT', 'ADMIN_LOCKED_OUT', 'ADMIN_CREATED', 'ADMIN_UPDATED', 'ADMIN_DEACTIVATED', 'ADMIN_PASSWORD_CHANGED', 'RESULTS_EXPORTED') NOT NULL;
